# Generated by Django 5.1.6 on 2025-02-24 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vylety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vylet',
            name='oblibene',
            field=models.ManyToManyField(blank=True, help_text='Uživatelé, kteří si výlet přidali do oblíbených', related_name='oblibene_vylety', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vylet',
            name='date',
            field=models.DateField(help_text='Datum konání výletu'),
        ),
        migrations.AlterField(
            model_name='vylet',
            name='description',
            field=models.TextField(help_text='Krátký popis výletu'),
        ),
        migrations.AlterField(
            model_name='vylet',
            name='name',
            field=models.CharField(help_text='Zadejte název výletu', max_length=200),
        ),
        migrations.AlterField(
            model_name='vylet',
            name='user',
            field=models.ForeignKey(help_text='Vlastník výletu', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
