# Generated by Django 5.1.6 on 2025-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clanek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulek', models.CharField(max_length=200)),
                ('obsah', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
