# Generated by Django 5.1.6 on 2025-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obrázek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('obrazek', models.ImageField(upload_to='galerie/')),
                ('popis', models.TextField(blank=True)),
                ('datum', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
