# Generated by Django 5.1.6 on 2025-02-24 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profily', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profilový obrázek uživatele', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='bio',
            field=models.TextField(blank=True, help_text='Krátký popis uživatele'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='uzivatel',
            field=models.OneToOneField(help_text='Uživatel, ke kterému tento profil patří', on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
    ]
