# Generated by Django 5.1.6 on 2025-02-24 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komentare', '0001_initial'),
        ('vylety', '0002_vylet_oblibene_alter_vylet_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='vylet',
            field=models.ForeignKey(default=1, help_text='Výlet, ke kterému komentář patří', on_delete=django.db.models.deletion.CASCADE, related_name='komentare', to='vylety.vylet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='komentar',
            name='datum',
            field=models.DateTimeField(auto_now_add=True, help_text='Datum vytvoření komentáře'),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='text',
            field=models.TextField(help_text='Obsah komentáře'),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='uzivatel',
            field=models.ForeignKey(help_text='Uživatel, který napsal komentář', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
